export * from './allocationEndpoint.service';
import { AllocationEndpointService } from './allocationEndpoint.service';
export * from './categoryEndpoint.service';
import { CategoryEndpointService } from './categoryEndpoint.service';
export * from './collegeEndpoint.service';
import { CollegeEndpointService } from './collegeEndpoint.service';
export * from './computerEndpoint.service';
import { ComputerEndpointService } from './computerEndpoint.service';
export * from './departmentEndpoint.service';
import { DepartmentEndpointService } from './departmentEndpoint.service';
export * from './employeeEndpoint.service';
import { EmployeeEndpointService } from './employeeEndpoint.service';
export * from './hoDEndpoint.service';
import { HoDEndpointService } from './hoDEndpoint.service';
export * from './microProfileHealth.service';
import { MicroProfileHealthService } from './microProfileHealth.service';
export * from './purchaseEndpoint.service';
import { PurchaseEndpointService } from './purchaseEndpoint.service';
export * from './qRCodePreviewEndpoint.service';
import { QRCodePreviewEndpointService } from './qRCodePreviewEndpoint.service';
export * from './supplierEndpoint.service';
import { SupplierEndpointService } from './supplierEndpoint.service';
export * from './transferEndpoint.service';
import { TransferEndpointService } from './transferEndpoint.service';
export const APIS = [AllocationEndpointService, CategoryEndpointService, CollegeEndpointService, ComputerEndpointService, DepartmentEndpointService, EmployeeEndpointService, HoDEndpointService, MicroProfileHealthService, PurchaseEndpointService, QRCodePreviewEndpointService, SupplierEndpointService, TransferEndpointService];
