/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AllocationStatus = 'ALLOCATED' | 'DEALLOCATED' | 'TRANSFERRED' | 'RETIRED' | 'RETURNED';

export const AllocationStatus = {
  Allocated: 'ALLOCATED' as AllocationStatus,
  Deallocated: 'DEALLOCATED' as AllocationStatus,
  Transferred: 'TRANSFERRED' as AllocationStatus,
  Retired: 'RETIRED' as AllocationStatus,
  Returned: 'RETURNED' as AllocationStatus
};

