/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * OpenAPI spec version: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AllocationStatus = 'ALLOCATED' | 'DEALLOCATED' | 'TRANSFERED' | 'RETIRED' | 'RETURNED';

export const AllocationStatus = {
    ALLOCATED: 'ALLOCATED' as AllocationStatus,
    DEALLOCATED: 'DEALLOCATED' as AllocationStatus,
    TRANSFERED: 'TRANSFERED' as AllocationStatus,
    RETIRED: 'RETIRED' as AllocationStatus,
    RETURNED: 'RETURNED' as AllocationStatus
};