/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * OpenAPI spec version: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Peripheral } from './peripheral';
import { Purchase } from './purchase';
import { QRCode } from './qRCode';

/**
 * Computer representation
 */
export interface Computer { 
    id?: number;
    brand: string;
    model: string;
    modelNumber: string;
    serialNumber: string;
    manufacturer: string;
    category?: Category;
    label?: QRCode;
    purchase: Purchase;
    processor: string;
    memory: number;
    storage: number;
    operatingSystem?: string;
    displaySize: number;
    graphicsCard?: number;
    peripherals: Array<Peripheral>;
}