/**
 * Electronic Asset Management APIs
 * We manage and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Purchase} from './purchase';
import {QRCode} from './qRCode';
import {Category} from './category';
import {Peripheral} from './peripheral';


/**
 * Computer representation
 */
export interface Computer {
  id?: number;
  brand: string;
  model: string;
  modelNumber: string;
  serialNumber: string;
  manufacturer: string;
  category?: Category;
  label?: QRCode;
  purchase: Purchase;
  createdAt?: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
  processor: string;
  memory: number;
  storage: number;
  operatingSystem?: string;
  displaySize: number;
  graphicsCard?: number;
  peripherals: Set<Peripheral>;
}

