/**
 * Electronic Asset Management APIs
 * We manage and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AllocationStatus} from './allocationStatus';
import {Employee} from './employee';
import {Asset} from './asset';


export interface EmployeeAsset {
  asset?: Asset;
  employee?: Employee;
  status?: AllocationStatus;
}

export namespace EmployeeAsset {
}


