/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EmploymentStatus =
  'CONTRACT'
  | 'PERMANENT'
  | 'FULL_TIME'
  | 'VOLUNTEER'
  | 'PROBATION'
  | 'INTERN'
  | 'PART_TIME'
  | 'TERMINATED'
  | 'FIRED'
  | 'LAID_OFF';

export const EmploymentStatus = {
  Contract: 'CONTRACT' as EmploymentStatus,
  Permanent: 'PERMANENT' as EmploymentStatus,
  FullTime: 'FULL_TIME' as EmploymentStatus,
  Volunteer: 'VOLUNTEER' as EmploymentStatus,
  Probation: 'PROBATION' as EmploymentStatus,
  Intern: 'INTERN' as EmploymentStatus,
  PartTime: 'PART_TIME' as EmploymentStatus,
  Terminated: 'TERMINATED' as EmploymentStatus,
  Fired: 'FIRED' as EmploymentStatus,
  LaidOff: 'LAID_OFF' as EmploymentStatus
};

