/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * OpenAPI spec version: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Gender = 'MALE' | 'FEMALE' | 'OTHER';

export const Gender = {
    MALE: 'MALE' as Gender,
    FEMALE: 'FEMALE' as Gender,
    OTHER: 'OTHER' as Gender
};