/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type HealthCheckStatus = 'DOWN' | 'UP';

export const HealthCheckStatus = {
    Down: 'DOWN' as HealthCheckStatus,
    Up: 'UP' as HealthCheckStatus
};

