/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Category } from './category';
import { Supplier } from './supplier';


export interface Item { 
    id?: number;
    itemName: string;
    qtyBought: number;
    status?: Status;
    datePurchased: string;
    transferCount?: number;
    description?: string;
    category?: Category;
    supplier?: Supplier;
}
export namespace Item {
}


