/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Peripheral = 'KEYBOARD' | 'MOUSE' | 'MONITOR' | 'ADAPTER' | 'COOLING_PAD';

export const Peripheral = {
  Keyboard: 'KEYBOARD' as Peripheral,
  Mouse: 'MOUSE' as Peripheral,
  Monitor: 'MONITOR' as Peripheral,
  Adapter: 'ADAPTER' as Peripheral,
  CoolingPad: 'COOLING_PAD' as Peripheral
};

