/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * OpenAPI spec version: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Peripheral = 'KEYBOARD' | 'MOUSE' | 'MONITOR' | 'ADAPTER' | 'COOLING_PAD';

export const Peripheral = {
    KEYBOARD: 'KEYBOARD' as Peripheral,
    MOUSE: 'MOUSE' as Peripheral,
    MONITOR: 'MONITOR' as Peripheral,
    ADAPTER: 'ADAPTER' as Peripheral,
    COOLINGPAD: 'COOLING_PAD' as Peripheral
};