/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * OpenAPI spec version: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalDate } from './localDate';
import { Supplier } from './supplier';

/**
 * Purchase representation
 */
export interface Purchase { 
    id?: number;
    purchaseDate: LocalDate;
    purchaseQty: number;
    purchasePrice: number;
    invoiceNumber: string;
    supplier?: Supplier;
    totalPurchaseCost?: number;
}