/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {Supplier} from './supplier';


/**
 * Purchase representation
 */
export interface Purchase {
  id?: number;
  purchaseDate: string;
  purchaseQty: number;
  purchasePrice: number;
  invoiceNumber: string;
  supplier?: Supplier;
  totalPurchaseCost?: number;
}

