/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Status = 'InStock' | 'InUse' | 'Faulty' | 'Retired' | 'New' | 'Transfered';

export const Status = {
    InStock: 'InStock' as Status,
    InUse: 'InUse' as Status,
    Faulty: 'Faulty' as Status,
    Retired: 'Retired' as Status,
    New: 'New' as Status,
    Transfered: 'Transfered' as Status
};

