/**
 * Electronic Asset Management APIs
 * We manage and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SupplierType = 'MANUFACTURER' | 'WHOLESALER' | 'RETAILER';

export const SupplierType = {
  Manufacturer: 'MANUFACTURER' as SupplierType,
  Wholesaler: 'WHOLESALER' as SupplierType,
  Retailer: 'RETAILER' as SupplierType
};

