/**
 * Electronic Asset Inventory API
 * We keep and organize inventory of all purchased electronic assets
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: luluyshaban@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AllocationStatus } from './allocationStatus';
import { Employee } from './employee';
import { Asset } from './asset';


/**
 * Transfer representation
 */
export interface Transfer { 
    id?: number;
    transferDate?: string;
    transferRemark?: string;
    status?: AllocationStatus;
    employee: Employee;
    newEmployee: Employee;
    asset: Asset;
}
export namespace Transfer {
}


